# Generated by Django 2.2.10 on 2020-05-03 18:56

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='title_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
